name: Continuous integration
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo test --all

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # for some reason clippy fails without libalsa
    - run: sudo apt-get install -y libasound2-dev
    - run: cargo clippy --all -- -D warnings
