name: WASM
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - run: wasm-pack build --target web
